import SwiftUI

public extension Color {
    static let primary1 = Color("primary1", bundle: .module)
    static let primary2 = Color("primary2", bundle: .module)
    static let primary3 = Color("primary3", bundle: .module)
    static let primary4 = Color("primary4", bundle: .module)
    static let secondary1 = Color("secondary1", bundle: .module)
    static let secondary2 = Color("secondary2", bundle: .module)
    static let secondary3 = Color("secondary3", bundle: .module)
    static let secondary4 = Color("secondary4", bundle: .module)
    static let neutral1 = Color("neutral1", bundle: .module)
    static let neutral2 = Color("neutral2", bundle: .module)
    static let neutral3 = Color("neutral3", bundle: .module)
    static let neutral4 = Color("neutral4", bundle: .module)
    static let neutral5 = Color("neutral5", bundle: .module)
    static let neutral6 = Color("neutral6", bundle: .module)
    static let neutral7 = Color("neutral7", bundle: .module)
    static let neutral8 = Color("neutral8", bundle: .module)
    static let glassDark = Color("glassDark", bundle: .module)

    // Specials
    static let skipButtonTint = Color("SkipButtonTint", bundle: .module)
    static let onboarding1Gradient1 = Color("onboarding1Gradient1", bundle: .module)
    static let onboarding1Gradient2 = Color("onboarding1Gradient2", bundle: .module)
    static let onboarding2Gradient1 = Color("onboarding2Gradient1", bundle: .module)
    static let onboarding2Gradient2 = Color("onboarding2Gradient2", bundle: .module)
    static let onboarding3Gradient1 = Color("onboarding3Gradient1", bundle: .module)
    static let onboarding3Gradient2 = Color("onboarding3Gradient2", bundle: .module)
    static let highlightedButtonSelected = Color("highlightedButtonSelected", bundle: .module)
    static let invisibleColor = Color.white.opacity(0.0001)
    static let connectWalletGradient1 = Color("connectWalletGradient1", bundle: .module)
    static let connectWalletGradient2 = Color("connectWalletGradient2", bundle: .module)
    static let stepperInactive = Color("stepperInactive", bundle: .module)
    static let connectWalletAlertBackground = Color("connectWalletAlertBackground", bundle: .module)
    static let connectWalletCancelBorder = Color("connectWalletCancelBorder", bundle: .module)
}
