# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

ENV["FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT"] = "180"

platform :ios do
  desc "Running tests"
  lane :run_appTests do
    scan(
      project: "NodeCrypto/NodeCrypto.xcodeproj",
      scheme: "CI", 
      device: "iPhone SE (3rd generation) (17.0)"
      )
  end
end
