# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:mac)

ENV["FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT"] = "180"

platform :mac do

  desc "Running tests"
  lane :run_appTests do
    sh("defaults write com.apple.dt.Xcode IDESkipMacroFingerprintValidation -bool YES")
    packages_path = "#{File.expand_path("..", Dir.pwd)}/packages_cache"
    scan(
      build_for_testing: true,
      project: "NodeCrypto/NodeCrypto.xcodeproj",
      scheme: "CI",
      cloned_source_packages_path: packages_path,
      disable_package_automatic_updates: true,
      skip_package_dependencies_resolution: ENV["HAS_PACKAGES_CACHE_HIT"],
    )
end
end