name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  mac:
    name: macOS
    runs-on: macOS-13
    steps:
    - uses: actions/checkout@v3
    # - name: Setup tmate session
    #   uses: mxschmitt/action-tmate@v2
    - name: Select Xcode 15.0.1
      run: sudo xcode-select -s /Applications/Xcode_15.0.1.app
    - name: Install yeetd
      run: |
       wget https://github.com/biscuitehh/yeetd/releases/download/1.0/yeetd-normal.pkg
       sudo installer -pkg yeetd-normal.pkg -target /
       yeetd &
    - name: Enable macro
      run: defaults write com.apple.dt.Xcode IDESkipMacroFingerprintValidation -bool YES
    - name: swift format
      run: |
          if [ -d ".build" ]; then
            if ! [ -x "$(command -v swift-format)" ]; then
              sudo cp -f .build/release/swift-format /usr/local/bin/swift-format
            fi
          else
            git clone -b swift-5.2-branch https://github.com/apple/swift-format.git
            cd swift-format
            swift build --disable-sandbox -c release
            mv .build .. && cd ..
            sudo cp -f .build/release/swift-format /usr/local/bin/swift-format
          fi
    - name: Install Fastlane
      run: |
           gem install fastlane
           fastlane env
    - name: Build and test with Fastlane
      run: fastlane run_appTests
   
