name: Build and run tests

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize]

jobs:
  test:
    name: Test
    runs-on: macos-13
    steps:
      - uses: maxim-lobanov/setup-xcode@v1.6.0
        with:
          xcode-version: latest-stable
      - name: Checkout repository
        uses: actions/checkout@v4.1.1
      - name: Cache packages
        uses: actions/cache@v3
        id: packages-cache
        with:
          path: packages_cache
          key: ${{ runner.os }}-packages-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-packages-
      - name: Enable macros
        run: defaults write com.apple.dt.Xcode IDESkipMacroFingerprintValidation -bool YES
      - name: Run tests
        run: ./build_scripts/test.sh
        env:
          HAS_PACKAGES_CACHE_HIT: ${{ steps.packages-cache.outputs.cache-hit == 'true' }}