name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

            - name: Apple Xcode Select
  # You may pin to the exact commit or the version.
  # uses: BoundfoxStudios/action-xcode-select@6db70aee8dc8f6f87fe25c6037f7e72d18464a59
  uses: BoundfoxStudios/action-xcode-select@v1
  with:
    # Version to use (like '11.7', '12' or simply 'latest')
    version: default # optional, default is latest
    # Whether to select a beta release or not. Beta releases may not always be available.
    beta: # optional, default is false
          

    - name: Build and test
      run: fastlane scan
