name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Xcode Select Version
      uses: MobileDevOps/xcode-select-version-action@v1.0.0
      with:
        xcode-select-version: latest-stable

    - name: Install Fastlane
      run: |
          gem install fastlane
          fastlane env

    - name: Build and test with Fastlane
      run: bundle exec fastlane scan --scheme NodeCrypto


