name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  mac:
    name: macOS
    runs-on: macOS-13
    steps:
    - uses: actions/checkout@v3
    # - name: Setup tmate session
    #   uses: mxschmitt/action-tmate@v2
    - name: Select Xcode 15.0.1
      run: sudo xcode-select -s /Applications/Xcode_15.0.1.app
    - name: Enable macro
      run: defaults write com.apple.dt.Xcode IDESkipMacroFingerprintValidation -bool YES
    - name: run tests
      run: |
        cd NodeCrypto
        xcodebuild test \
          -project NodeCrypto.xcodeproj \
          -scheme CI \
          -destination 'platform=iOS Simulator,name=iPhone SE (3rd generation),OS=17.0'
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGN_ENTITLEMENTS="" \
          CODE_SIGNING_ALLOWED=NO
    # - name: Install Fastlane
    #   run: |
    #       gem install fastlane
    #       fastlane env
   
