name: Build and run tests

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize]

jobs:
  test:
    name: Test
    runs-on: macos-latest
    steps:
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest

      - name: Checkout repository
        uses: actions/checkout@v4.1.1

      - name: Restore cached packages
        id: cache-packages-restore
        uses: actions/cache/restore@v4
        with:
          key: ${{ runner.os }}-packages
          path: packages  # Verify this path matches your project's dependency location

      - name: Resolve Swift Package Dependencies
        run: xcodebuild -resolvePackageDependencies -project NodeCrypto/NodeCrypto.xcodeproj

      - name: Save packages cache
        if: steps.cache-packages-restore.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          key: ${{ runner.os }}-packages
          path: packages  # Verify this path matches your project's dependency location

      - name: Enable macros
        run: defaults write com.apple.dt.Xcode IDESkipMacroFingerprintValidation -bool YES
        # Consider removing if not necessary for your project

      - name: Run tests
        run: ./build_scripts/test.sh
        env:
          HAS_PACKAGES_CACHE_HIT: ${{ steps.cache-packages-restore.outputs.cache-hit == 'true' }}
