name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Xcode Select Version
      uses: MobileDevOps/xcode-select-version-action@v1.0.0
            
    - name: Build and test
      run: fastlane scan
