name: Build and run tests

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize]

jobs:
  test:
    name: Test
    runs-on: macos-latest
    steps:
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest

      - name: Checkout repository
        uses: actions/checkout@v4.1.1

      - name: List available simulators
        run: xcrun simctl list devices

      - name: Run tests
        run: xcodebuild test -project NodeCrypto/NodeCrypto.xcodeproj -scheme NodeCrypto -destination 'platform=iOS Simulator,name=iPhone 15,OS='18.2''
