name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Xcode Select Version
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.0-beta'

    - name: Install Fastlane
      run: |
          gem install fastlane
          fastlane env

    - name: Build and test with Fastlane
      run:  fastlane scan --scheme NodeCrypto


